### ISSUE TITLE
-tで指定するファイルの場所について

### ISSUE THREAD

**Issue by conao3** [online-judge-tools/template-generator#10]
> oj-template のためのテンプレートは ~/.config/online-judge-tools/template/ の下に ~/.config/online-judge-tools/template/customized.py のように作って oj-template -t customized.py https://... のように指定する。 

ファイル名に `/` が含まれることはないので、 `/` が含まれている場合、
パスが指定されていると推測しても問題ないと思います。

具体的には一つ上の階層にtempate-ext.cppを作った上で
```shell
oj-template https://codeforces.com/contest/1349/problem/A -t ../template-ext.cpp
```
と実行したいです。

こうすることで[coder](https://github.com/conao3/coder)のようにオンラインジャッジの
作業フォルダを全部GitHubに上げている場合に、そのフォルダだけで情報を管理できるようになります。

ご検討頂ければと思います。

**Comment by kmyk** [comment]
よさそうです。
実際、Unix 環境のコマンドの実体の検索方法はこのような方式になっていてかつ上手く動いています ([man execvp](https://linuxjm.osdn.jp/html/LDP_man-pages/man3/exec.3.html))。動作の分かりやすさの上でも、慣習と合致しているこちらの方式の方が優れているでしょう。
テンプレートエンジンの内部の記法 (`<%include file="..." />` など) との整合性が取れなくなるという欠点はありますが、これで困ることはなく無視してもよいはずです。

しばらく後になると思いますが、そのうち実装しておきます。早めに実装してほしい場合はプルリクをお願いします。
